### ISSUE TITLE
Long energy mix names push the date value out of sight

### ISSUE THREAD

**Issue by twilkinson573** [quintel/energymixer#236]
Entering long values when naming your energy mix pushes the date value out of the card and out of sight.
Long names are shortened with an ellipsis, however the cut off should be shorter.
This was an issue on all browsers/monitor sizes.
(http://mixer.energytransitionmodel.com/mixes)

![image](https://cloud.githubusercontent.com/assets/6432221/5817412/e3efc70a-a0ab-11e4-9c73-fb8f468b2ab1.png)

**Comment by ChaelKruip** [comment]
Assigned to @twilkinson573

**Comment by twilkinson573** [comment]
Fixed in 9b111aaa3aeab5297389f90ba130f5c1c1b24381
